"""Initial database schema

Revision ID: 4eabc8697903
Revises: 
Create Date: 2025-09-19 10:05:41.706014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eabc8697903'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blob',
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('version',
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('message_json', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('hash')
    )
    with op.batch_alter_table('version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_version_timestamp'), ['timestamp'], unique=False)

    op.create_table('version_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_hash', sa.String(length=64), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('blob_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['blob_hash'], ['blob.hash'], ),
    sa.ForeignKeyConstraint(['version_hash'], ['version.hash'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('version_file')
    with op.batch_alter_table('version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_version_timestamp'))

    op.drop_table('version')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('blob')
    # ### end Alembic commands ###
